[functions]
  node_bundler = "esbuild"

[functions."snapshot_avis"]
  schedule = "0 3 */2 * *"

[functions."snapshot_rank"]
  schedule = "50 5 * * 1,4"

[functions."snapshot_rank_b"]
  schedule = "53 5 * * 1,4"

[functions."snapshot_rank_c"]
  schedule = "56 5 * * 1,4"

[functions."snapshot_rank_d"]
  schedule = "59 5 * * 1,4"
